// <auto-generated>
//     This code was generated by Refitter.
//     Temporary stub - will be replaced when actual client generation runs successfully.
// </auto-generated>

using Refit;
using System.Threading.Tasks;

#nullable enable annotations

namespace Zarichney.Client
{
    /// <summary>
    /// Temporary stub interface for API endpoints
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Refitter", "1.5.5.0")]
    public partial interface IApiApi
    {
        /// <summary>
        /// Temporary stub method - will be replaced when actual client generation runs successfully.
        /// </summary>
        [Get("/api/stub")]
        Task<object> StubMethod();

        /// <summary>
        /// Stub for Secure method
        /// </summary>
        [Get("/api/health/secure")]
        Task Secure();
    }
}