// <auto-generated>
//     This code was generated by Refitter.
//     Temporary stub - will be replaced when actual client generation runs successfully.
// </auto-generated>

using Refit;
using System.Collections.Generic;
using System.Threading.Tasks;

#nullable enable annotations

namespace Zarichney.Client
{
    /// <summary>
    /// Temporary stub interface for Cookbook API endpoints
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Refitter", "1.5.5.0")]
    public partial interface ICookbookApi
    {
        /// <summary>
        /// Temporary stub method - will be replaced when actual client generation runs successfully.
        /// </summary>
        [Get("/api/cookbook/stub")]
        Task<object> StubMethod();

        /// <summary>
        /// Stub for Recipe method
        /// </summary>
        [Get("/api/recipe")]
        Task<ICollection<Recipe>> Recipe(string query, bool scrape, int? acceptableScore, int? requiredCount);
    }
}