// <auto-generated>
//     This code was generated by Refitter.
//     Temporary stub - will be replaced when actual client generation runs successfully.
// </auto-generated>

using Refit;
using System.Threading.Tasks;

#nullable enable annotations

namespace Zarichney.Client
{
    /// <summary>
    /// Temporary stub interface for Payment API endpoints
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Refitter", "1.5.5.0")]
    public partial interface IPaymentApi
    {
        /// <summary>
        /// Temporary stub method - will be replaced when actual client generation runs successfully.
        /// </summary>
        [Get("/api/payments/stub")]
        Task<object> StubMethod();

        /// <summary>
        /// Stub for CreateIntent method
        /// </summary>
        [Post("/api/payments/create-intent")]
        Task CreateIntent([Body] PaymentIntentRequest request);

        /// <summary>
        /// Stub for Status method
        /// </summary>
        [Get("/api/payments/status")]
        Task Status(string paymentIntentId);
    }
}