// <auto-generated>
//     This code was generated by Refitter.
//     Temporary stub - will be replaced when actual client generation runs successfully.
// </auto-generated>

using Refit;
using System.Collections.Generic;
using System.Threading.Tasks;

#nullable enable annotations

namespace Zarichney.Client
{
    /// <summary>
    /// Temporary stub interface for Public API endpoints
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Refitter", "1.5.5.0")]
    public partial interface IPublicApi
    {
        /// <summary>
        /// Temporary stub method - will be replaced when actual client generation runs successfully.
        /// </summary>
        [Get("/api/public/stub")]
        Task<object> StubMethod();

        /// <summary>
        /// Stub for Health method
        /// </summary>
        [Get("/api/health")]
        Task Health();

        /// <summary>
        /// Stub for Config method
        /// </summary>
        [Get("/api/config")]
        Task<ICollection<ConfigurationItemStatus>> Config();

        /// <summary>
        /// Stub for StatusAll method
        /// </summary>
        [Get("/api/status")]
        Task<ICollection<ServiceStatusInfo>> StatusAll();
    }
}