-- Create ApiKeys table
CREATE TABLE IF NOT EXISTS "ApiKeys" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "KeyValue" character varying(64) NOT NULL,
    "Name" character varying(100) NOT NULL,
    "CreatedAt" timestamp NOT NULL DEFAULT (now() at time zone 'utc'),
    "ExpiresAt" timestamp NULL,
    "IsActive" boolean NOT NULL DEFAULT TRUE,
    "Description" character varying(255) NULL,
    "UserId" character varying(450) NOT NULL,
    CONSTRAINT "PK_ApiKeys" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ApiKeys_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

-- Create index on KeyValue for fast lookups
CREATE UNIQUE INDEX IF NOT EXISTS "IX_ApiKeys_KeyValue" ON "ApiKeys" ("KeyValue");

-- Create index on UserId for fast lookups
CREATE INDEX IF NOT EXISTS "IX_ApiKeys_UserId" ON "ApiKeys" ("UserId");

-- Update migration history
INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250324000001_AddApiKeysTable', '8.0.14')
ON CONFLICT ("MigrationId") DO NOTHING;