name: 'Post Analysis Results'
description: 'Unified posting of analysis results to pull requests'
author: 'Zarichney Development'

inputs:
  pr-number:
    description: 'Pull request number'
    required: true
  report-file:
    description: 'Path to the markdown report file'
    required: true
  report-type:
    description: 'Type of report (security, quality, test)'
    required: true
  github-token:
    description: 'GitHub token for API access'
    required: true
  update-existing:
    description: 'Whether to update existing comment or create new'
    required: false
    default: 'true'

outputs:
  comment-id:
    description: 'ID of the created or updated comment'
    value: ${{ steps.post-comment.outputs.comment-id }}
  comment-url:
    description: 'URL of the created or updated comment'
    value: ${{ steps.post-comment.outputs.comment-url }}

runs:
  using: 'composite'
  steps:
    - name: Validate inputs
      shell: bash
      run: |
        if [ ! -f "${{ inputs.report-file }}" ]; then
          echo "❌ Report file not found: ${{ inputs.report-file }}"
          exit 1
        fi
        
        echo "✅ Report file validated: ${{ inputs.report-file }}"
        echo "📄 Report type: ${{ inputs.report-type }}"
        echo "🔗 PR number: ${{ inputs.pr-number }}"

    - name: Post or update PR comment
      id: post-comment
      uses: marocchino/sticky-pull-request-comment@v2
      with:
        number: ${{ inputs.pr-number }}
        recreate: ${{ inputs.update-existing }}
        path: ${{ inputs.report-file }}
        header: ${{ inputs.report-type }}-analysis
        GITHUB_TOKEN: ${{ inputs.github-token }}

    - name: Log comment details
      shell: bash
      run: |
        echo "📝 Comment posted successfully:"
        echo "  - Comment ID: ${{ steps.post-comment.outputs.comment-id }}"
        echo "  - Comment URL: ${{ steps.post-comment.outputs.comment-url }}"
        echo "  - Report Type: ${{ inputs.report-type }}"
        echo "  - Update Mode: ${{ inputs.update-existing }}"