name: 'Check Existing AI Analysis Comment'
description: 'Detects if a PR already has a specific AI analysis comment by header and sets skip flag.'
inputs:
  github-token:
    description: 'GitHub token with repo access'
    required: true
  header:
    description: 'Canonical header string to detect in PR comments'
    required: true
outputs:
  skip_analysis:
    description: 'true if an existing analysis comment was found, else false'
    value: ${{ steps.detect.outputs.skip_analysis }}
runs:
  using: 'composite'
  steps:
    - name: Detect existing analysis comment
      id: detect
      uses: actions/github-script@v7
      with:
        github-token: ${{ inputs.github-token }}
        script: |
          // Get all comments on this PR
          const comments = await github.rest.issues.listComments({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number,
          });

          const header = core.getInput('header', { required: true });

          const hasExistingAnalysis = comments.data.some(comment => {
            const body = comment.body || '';
            return (
              body.includes(header) &&
              !body.includes('Claude encountered an error') &&
              !body.includes('Analysis Failed') &&
              (body.includes('Status:') || body.includes('Do Now') || body.includes('Do Later'))
            );
          });

          core.info(`Found existing analysis for [${header}]: ${hasExistingAnalysis}`);
          core.setOutput('skip_analysis', String(hasExistingAnalysis));
