#!/bin/bash

# Pre-commit validation script to help prevent generated file contamination
# This script can be used manually or integrated into git hooks

set -e

echo "🔍 Pre-commit validation for generated files..."

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Check for large files in staging area
echo "📊 Checking for large files in staging area..."
large_files=$(git diff --cached --numstat | awk '$1 > 1000 || $2 > 1000 {print $3, "(" $1 " additions, " $2 " deletions)"}')

if [ -n "$large_files" ]; then
    echo -e "${YELLOW}⚠️  Warning: Large files detected in staging area:${NC}"
    echo "$large_files"
    echo ""
    echo -e "${YELLOW}Please verify these files should be committed.${NC}"
    echo -e "${YELLOW}If they are generated files, consider if they should be in .gitignore${NC}"
    echo ""
fi

# Check for common generated file patterns that might slip through
echo "🚫 Checking for potential generated files..."
generated_files=$(git diff --cached --name-only | grep -E '\.(json|yaml|yml)$' | grep -iE '(swagger|openapi)' || true)

if [ -n "$generated_files" ]; then
    echo -e "${RED}❌ Error: Potential generated API documentation files detected:${NC}"
    echo "$generated_files"
    echo ""
    echo -e "${RED}These files should typically not be committed.${NC}"
    echo "Consider adding them to .gitignore or removing them from staging."
    exit 1
fi

# Check for auto-generated code markers
echo "🤖 Checking for auto-generated code modifications..."
auto_generated=$(git diff --cached | grep -l "auto-generated\|<auto-generated>" || true)

if [ -n "$auto_generated" ]; then
    echo -e "${YELLOW}⚠️  Warning: Changes detected in auto-generated files.${NC}"
    echo -e "${YELLOW}Please verify these changes are intentional.${NC}"
    echo -e "${YELLOW}Auto-generated files should typically not be manually edited.${NC}"
    echo ""
fi

# Check total line changes
total_changes=$(git diff --cached --numstat | awk '{added+=$1; deleted+=$2} END {print added+deleted}')

if [ "$total_changes" -gt 5000 ]; then
    echo -e "${YELLOW}⚠️  Warning: Large commit detected ($total_changes total line changes).${NC}"
    echo -e "${YELLOW}Please verify this is expected and not due to generated file inclusion.${NC}"
    echo ""
fi

echo -e "${GREEN}✅ Pre-commit validation completed.${NC}"

# Show summary of what's being committed
echo ""
echo "📋 Summary of changes to be committed:"
git diff --cached --stat

echo ""
echo -e "${GREEN}If everything looks correct, proceed with your commit.${NC}"
echo -e "${GREEN}If you see unexpected generated files, use 'git reset HEAD <file>' to unstage them.${NC}"