name: Test Results Reporter

on:
  workflow_run:
    workflows: ["Unified CI/CD for Zarichney Fullstack"]
    types:
      - completed

permissions:
  checks: write
  pull-requests: write
  contents: read
  actions: read

jobs:
  report:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.event == 'pull_request' && github.event.workflow_run.conclusion == 'success'
    
    steps:
      - name: Download backend test results
        uses: actions/download-artifact@v4
        with:
          name: backend-test-results
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}
          
      - name: Download backend coverage artifacts
        uses: actions/download-artifact@v4
        with:
          name: backend-coverage-results
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}

      - name: Publish Backend Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          trx_files: "**/*.trx"
          check_name: "Backend Test Results"
          comment_title: "Backend Test Results"
          
      - name: Backend Code Coverage Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: "**/coverage.cobertura.xml"
          badge: true
          format: markdown
          output: both
          
      - name: Add Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event.workflow_run.event == 'pull_request'
        with:
          recreate: true
          path: code-coverage-results.md