name: Test Results Reporter

on:
  workflow_run:
    workflows: ["Build, Test and Deploy Zarichney API"]
    types:
      - completed

permissions:
  checks: write
  pull-requests: write
  contents: read
  actions: read

jobs:
  report:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.event == 'pull_request'
    
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: test-results
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}
          
      - name: Download coverage artifacts
        uses: actions/download-artifact@v4
        with:
          name: coverage-results
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          trx_files: "**/*.trx"
          check_name: "Test Results"
          comment_title: "Test Results"
          
      - name: Code Coverage Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: "**/coverage.cobertura.xml"
          badge: true
          format: markdown
          output: both
          
      - name: Add Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event.workflow_run.event == 'pull_request'
        with:
          recreate: true
          path: code-coverage-results.md